### ISSUE TITLE
大佬，我复制安装的过程中出现几个问题，您看看

### ISSUE THREAD

**Issue by huiyehai** [leadream/wedding-invitation-for-programmers#15]
一、yran install 会报错，然后全部以sudo yarn的时候解决了，我想这个权限问题，但是小白一个，能安装也好也可以，还是想问下修改
二、yarn serve 后 network的网址进不去是端口的原因吗？
三、1、yarn lint 网页显示空页面，在所有src后面添加 ./ 界面才显示出来
![image](https://user-images.githubusercontent.com/42177640/71781858-73e0a900-300e-11ea-96e9-658645be424c.png)

2、打开邀请函的图片，修改这里无效，将img文件夹放到根目录下才显示出来
![image](https://user-images.githubusercontent.com/42177640/71781865-95419500-300e-11ea-9c82-19a120d803d9.png)
![image](https://user-images.githubusercontent.com/42177640/71781872-9e326680-300e-11ea-8ee5-b6b4e2e701fd.png)

四、最后一个就是这个修改内容的界面在怎么进入呢,看文件夹也没有进入的路径
![image](https://user-images.githubusercontent.com/42177640/71781877-a7bbce80-300e-11ea-9595-c76ba064cb07.png)

**Comment by leadream** [comment]
@huiyehai 
克隆之后执行 `yarn serve` 在终端会提示你啊，这俩就是本地访问的地址。
![image](https://user-images.githubusercontent.com/12868055/71792978-cef9b680-3075-11ea-90ed-f27783f961bc.png)

`yarn lint` 是测试，一般来说本地开发是 `yarn serve`，构建静态文件是 `yarn build`，不需要跑测试啊。

你要修改代码改源码啊，改完之后再编译，编译之后的代码没人看得懂的。
